/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class CarTest {
    @Test public void testAppHasAGreeting() {
        //App classUnderTest = new App();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        Automobile auto = new Automobile();

        auto.x = 5;
        assertEquals(5, auto.x);
    }
}
